apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80



=========================================================


commands:
First save the above lines in a file as nginx-deploymnet.yaml
kubectl apply -f nginx-deploymnet.yaml
kubectl get pods
kubectl get service
minikube service nginx-service --url

curl http://192.168.49.2:31374

Make sure the port number and IP is correct
